/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as AppRouteImport } from './app/_app'
import { Route as OnboardingIndexRouteImport } from './app/onboarding/index'
import { Route as AppIndexRouteImport } from './app/_app/index'
import { Route as OnboardingPainPointsRouteImport } from './app/onboarding/pain-points'
import { Route as OnboardingInputMethodRouteImport } from './app/onboarding/input-method'
import { Route as OnboardingGoalRouteImport } from './app/onboarding/goal'
import { Route as OnboardingDoneRouteImport } from './app/onboarding/done'
import { Route as AuthSignUpRouteImport } from './app/auth/sign-up'
import { Route as AuthSignInRouteImport } from './app/auth/sign-in'
import { Route as AppWrappedRouteImport } from './app/_app/wrapped'
import { Route as AppTransactionsRouteImport } from './app/_app/transactions'
import { Route as AppPanicRouteImport } from './app/_app/panic'
import { Route as AppChallengeRouteImport } from './app/_app/challenge'
import { Route as AppAddExpenseRouteImport } from './app/_app/add-expense'
import { Route as AppAccountsRouteImport } from './app/_app/accounts'
import { Route as AppSubscriptionsIndexRouteImport } from './app/_app/subscriptions/index'
import { Route as AppGoalsIndexRouteImport } from './app/_app/goals/index'
import { Route as AppSubscriptionsIdRouteImport } from './app/_app/subscriptions/$id'
import { Route as AppGoalsNewRouteImport } from './app/_app/goals/new'
import { Route as AppGoalsIdRouteImport } from './app/_app/goals/$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const OnboardingPainPointsRoute = OnboardingPainPointsRouteImport.update({
  id: '/onboarding/pain-points',
  path: '/onboarding/pain-points',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingInputMethodRoute = OnboardingInputMethodRouteImport.update({
  id: '/onboarding/input-method',
  path: '/onboarding/input-method',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingGoalRoute = OnboardingGoalRouteImport.update({
  id: '/onboarding/goal',
  path: '/onboarding/goal',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDoneRoute = OnboardingDoneRouteImport.update({
  id: '/onboarding/done',
  path: '/onboarding/done',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWrappedRoute = AppWrappedRouteImport.update({
  id: '/wrapped',
  path: '/wrapped',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppPanicRoute = AppPanicRouteImport.update({
  id: '/panic',
  path: '/panic',
  getParentRoute: () => AppRoute,
} as any)
const AppChallengeRoute = AppChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => AppRoute,
} as any)
const AppAddExpenseRoute = AppAddExpenseRouteImport.update({
  id: '/add-expense',
  path: '/add-expense',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionsIndexRoute = AppSubscriptionsIndexRouteImport.update({
  id: '/subscriptions/',
  path: '/subscriptions/',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsIndexRoute = AppGoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionsIdRoute = AppSubscriptionsIdRouteImport.update({
  id: '/subscriptions/$id',
  path: '/subscriptions/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsNewRoute = AppGoalsNewRouteImport.update({
  id: '/goals/new',
  path: '/goals/new',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsIdRoute = AppGoalsIdRouteImport.update({
  id: '/goals/$id',
  path: '/goals/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/accounts': typeof AppAccountsRoute
  '/add-expense': typeof AppAddExpenseRoute
  '/challenge': typeof AppChallengeRoute
  '/panic': typeof AppPanicRoute
  '/transactions': typeof AppTransactionsRoute
  '/wrapped': typeof AppWrappedRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/onboarding/done': typeof OnboardingDoneRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/input-method': typeof OnboardingInputMethodRoute
  '/onboarding/pain-points': typeof OnboardingPainPointsRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/goals/$id': typeof AppGoalsIdRoute
  '/goals/new': typeof AppGoalsNewRoute
  '/subscriptions/$id': typeof AppSubscriptionsIdRoute
  '/goals/': typeof AppGoalsIndexRoute
  '/subscriptions/': typeof AppSubscriptionsIndexRoute
}
export interface FileRoutesByTo {
  '/accounts': typeof AppAccountsRoute
  '/add-expense': typeof AppAddExpenseRoute
  '/challenge': typeof AppChallengeRoute
  '/panic': typeof AppPanicRoute
  '/transactions': typeof AppTransactionsRoute
  '/wrapped': typeof AppWrappedRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/onboarding/done': typeof OnboardingDoneRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/input-method': typeof OnboardingInputMethodRoute
  '/onboarding/pain-points': typeof OnboardingPainPointsRoute
  '/': typeof AppIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/goals/$id': typeof AppGoalsIdRoute
  '/goals/new': typeof AppGoalsNewRoute
  '/subscriptions/$id': typeof AppSubscriptionsIdRoute
  '/goals': typeof AppGoalsIndexRoute
  '/subscriptions': typeof AppSubscriptionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/accounts': typeof AppAccountsRoute
  '/_app/add-expense': typeof AppAddExpenseRoute
  '/_app/challenge': typeof AppChallengeRoute
  '/_app/panic': typeof AppPanicRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_app/wrapped': typeof AppWrappedRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/onboarding/done': typeof OnboardingDoneRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/input-method': typeof OnboardingInputMethodRoute
  '/onboarding/pain-points': typeof OnboardingPainPointsRoute
  '/_app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_app/goals/$id': typeof AppGoalsIdRoute
  '/_app/goals/new': typeof AppGoalsNewRoute
  '/_app/subscriptions/$id': typeof AppSubscriptionsIdRoute
  '/_app/goals/': typeof AppGoalsIndexRoute
  '/_app/subscriptions/': typeof AppSubscriptionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/add-expense'
    | '/challenge'
    | '/panic'
    | '/transactions'
    | '/wrapped'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/onboarding/done'
    | '/onboarding/goal'
    | '/onboarding/input-method'
    | '/onboarding/pain-points'
    | '/onboarding/'
    | '/goals/$id'
    | '/goals/new'
    | '/subscriptions/$id'
    | '/goals/'
    | '/subscriptions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accounts'
    | '/add-expense'
    | '/challenge'
    | '/panic'
    | '/transactions'
    | '/wrapped'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/onboarding/done'
    | '/onboarding/goal'
    | '/onboarding/input-method'
    | '/onboarding/pain-points'
    | '/'
    | '/onboarding'
    | '/goals/$id'
    | '/goals/new'
    | '/subscriptions/$id'
    | '/goals'
    | '/subscriptions'
  id:
    | '__root__'
    | '/_app'
    | '/_app/accounts'
    | '/_app/add-expense'
    | '/_app/challenge'
    | '/_app/panic'
    | '/_app/transactions'
    | '/_app/wrapped'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/onboarding/done'
    | '/onboarding/goal'
    | '/onboarding/input-method'
    | '/onboarding/pain-points'
    | '/_app/'
    | '/onboarding/'
    | '/_app/goals/$id'
    | '/_app/goals/new'
    | '/_app/subscriptions/$id'
    | '/_app/goals/'
    | '/_app/subscriptions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  OnboardingDoneRoute: typeof OnboardingDoneRoute
  OnboardingGoalRoute: typeof OnboardingGoalRoute
  OnboardingInputMethodRoute: typeof OnboardingInputMethodRoute
  OnboardingPainPointsRoute: typeof OnboardingPainPointsRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/onboarding/pain-points': {
      id: '/onboarding/pain-points'
      path: '/onboarding/pain-points'
      fullPath: '/onboarding/pain-points'
      preLoaderRoute: typeof OnboardingPainPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/input-method': {
      id: '/onboarding/input-method'
      path: '/onboarding/input-method'
      fullPath: '/onboarding/input-method'
      preLoaderRoute: typeof OnboardingInputMethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/goal': {
      id: '/onboarding/goal'
      path: '/onboarding/goal'
      fullPath: '/onboarding/goal'
      preLoaderRoute: typeof OnboardingGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/done': {
      id: '/onboarding/done'
      path: '/onboarding/done'
      fullPath: '/onboarding/done'
      preLoaderRoute: typeof OnboardingDoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wrapped': {
      id: '/_app/wrapped'
      path: '/wrapped'
      fullPath: '/wrapped'
      preLoaderRoute: typeof AppWrappedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/panic': {
      id: '/_app/panic'
      path: '/panic'
      fullPath: '/panic'
      preLoaderRoute: typeof AppPanicRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/challenge': {
      id: '/_app/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof AppChallengeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/add-expense': {
      id: '/_app/add-expense'
      path: '/add-expense'
      fullPath: '/add-expense'
      preLoaderRoute: typeof AppAddExpenseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts': {
      id: '/_app/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscriptions/': {
      id: '/_app/subscriptions/'
      path: '/subscriptions'
      fullPath: '/subscriptions/'
      preLoaderRoute: typeof AppSubscriptionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals/': {
      id: '/_app/goals/'
      path: '/goals'
      fullPath: '/goals/'
      preLoaderRoute: typeof AppGoalsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscriptions/$id': {
      id: '/_app/subscriptions/$id'
      path: '/subscriptions/$id'
      fullPath: '/subscriptions/$id'
      preLoaderRoute: typeof AppSubscriptionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals/new': {
      id: '/_app/goals/new'
      path: '/goals/new'
      fullPath: '/goals/new'
      preLoaderRoute: typeof AppGoalsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/goals/$id': {
      id: '/_app/goals/$id'
      path: '/goals/$id'
      fullPath: '/goals/$id'
      preLoaderRoute: typeof AppGoalsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountsRoute: typeof AppAccountsRoute
  AppAddExpenseRoute: typeof AppAddExpenseRoute
  AppChallengeRoute: typeof AppChallengeRoute
  AppPanicRoute: typeof AppPanicRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppWrappedRoute: typeof AppWrappedRoute
  AppIndexRoute: typeof AppIndexRoute
  AppGoalsIdRoute: typeof AppGoalsIdRoute
  AppGoalsNewRoute: typeof AppGoalsNewRoute
  AppSubscriptionsIdRoute: typeof AppSubscriptionsIdRoute
  AppGoalsIndexRoute: typeof AppGoalsIndexRoute
  AppSubscriptionsIndexRoute: typeof AppSubscriptionsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountsRoute: AppAccountsRoute,
  AppAddExpenseRoute: AppAddExpenseRoute,
  AppChallengeRoute: AppChallengeRoute,
  AppPanicRoute: AppPanicRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppWrappedRoute: AppWrappedRoute,
  AppIndexRoute: AppIndexRoute,
  AppGoalsIdRoute: AppGoalsIdRoute,
  AppGoalsNewRoute: AppGoalsNewRoute,
  AppSubscriptionsIdRoute: AppSubscriptionsIdRoute,
  AppGoalsIndexRoute: AppGoalsIndexRoute,
  AppSubscriptionsIndexRoute: AppSubscriptionsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  OnboardingDoneRoute: OnboardingDoneRoute,
  OnboardingGoalRoute: OnboardingGoalRoute,
  OnboardingInputMethodRoute: OnboardingInputMethodRoute,
  OnboardingPainPointsRoute: OnboardingPainPointsRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
